//
//  MainViewController.swift
//  currency_btc
//
//  Created Phattarapon Jungtakarn on 19/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainViewController: UIViewController {

	var presenter: MainPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        self.initUI()
    }
    
    func initUI() {
        self.attachModule(vc: TabbarRouter.createModule(), toView: self.view)
    }
    
    func setupNavigationBar() {
        self.navigationController?.navigationBar.isHidden = false
    }

}

extension MainViewController: MainViewProtocol {
    
    func displayTabbarChange() {
        self.attachModule(vc: TabbarRouter.createModule(), toView: self.view)
    }
    
}
