//
//  MainProtocols.swift
//  currency_btc
//
//  Created Phattarapon Jungtakarn on 19/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MainWireframeProtocol: class {

}
//MARK: Presenter -
protocol MainPresenterProtocol: class {

}

//MARK: Interactor -
protocol MainInteractorProtocol: class {
    var presenter: MainPresenterProtocol?  { get set }
}

//MARK: View -
protocol MainViewProtocol: class {
    var presenter: MainPresenterProtocol?  { get set }
    func displayTabbarChange()
}
