//
//  HistoryProtocols.swift
//  currency_btc
//
//  Created Phattarapon Jungtakarn on 20/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HistoryWireframeProtocol: class {

}
//MARK: Presenter -
protocol HistoryPresenterProtocol: class {
    func notifyFetchHistoryCurrencyBitcoin()
    func notifyDisplayHistoryCurrencyBitcoin(currencyData: [BitcoinEntity])
}

//MARK: Interactor -
protocol HistoryInteractorProtocol: class {
    var presenter: HistoryPresenterProtocol?  { get set }
    func fetchHistoryCurrencyBitcoin()
}

//MARK: View -
protocol HistoryViewProtocol: class {
    var presenter: HistoryPresenterProtocol?  { get set }
    func displayHistoryCurrencyBitcoin(currencyData: [BitcoinEntity])
}
