//
//  HistoryInteractor.swift
//  currency_btc
//
//  Created Phattarapon Jungtakarn on 20/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryInteractor {

    weak var presenter: HistoryPresenterProtocol?
    var currencyBitcoinData: [BitcoinEntity] = []
    
    init() {
        self.startUpdatingData()
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    func startUpdatingData() {
        Timer.scheduledTimer(timeInterval: 60.0, target: self, selector: #selector(updateData), userInfo: nil, repeats: true)
    }
    
    @objc func updateData() {
        self.fetchHistoryCurrencyBitcoin()
    }
    
}

extension HistoryInteractor: HistoryInteractorProtocol {
    
    func fetchHistoryCurrencyBitcoin() {
        if let healthCurrencyBitcoin = DBHistoryCurrencyBitcoinHelper.shared.selectCurrencyBitcoin() {
            for data in healthCurrencyBitcoin {
                if let jsonResult = data.currency_bitcoin_data.dictionary() {
                    if let currencyBitcoinData = BitcoinEntity.from(jsonResult) {
                        self.currencyBitcoinData.append(currencyBitcoinData)
                    }
                }
            }
            self.presenter?.notifyDisplayHistoryCurrencyBitcoin(currencyData: self.currencyBitcoinData)
        } else {
            print("error get data")
        }
    }
    
}
