//
//  HistoryRouter.swift
//  currency_btc
//
//  Created Phattarapon Jungtakarn on 20/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryRouter {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = HistoryViewController(nibName: nil, bundle: nil)
        let interactor = HistoryInteractor()
        let router = HistoryRouter()
        let presenter = HistoryPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        view.setTabbarImage("ic_history", title: "History")
        
        return view
    }
}

extension HistoryRouter: HistoryWireframeProtocol {
    
}
