//
//  HistoryPresenter.swift
//  currency_btc
//
//  Created Phattarapon Jungtakarn on 20/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryPresenter {

    weak private var view: HistoryViewProtocol?
    var interactor: HistoryInteractorProtocol?
    private let router: HistoryWireframeProtocol

    init(interface: HistoryViewProtocol, interactor: HistoryInteractorProtocol?, router: HistoryWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension HistoryPresenter: HistoryPresenterProtocol {
    
    func notifyFetchHistoryCurrencyBitcoin() {
        self.interactor?.fetchHistoryCurrencyBitcoin()
    }
    
    func notifyDisplayHistoryCurrencyBitcoin(currencyData: [BitcoinEntity]) {
        self.view?.displayHistoryCurrencyBitcoin(currencyData: currencyData)
    }
    
}
