//
//  CurrencyPresenter.swift
//  currency_btc
//
//  Created Phattarapon Jungtakarn on 19/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CurrencyPresenter {

    weak private var view: CurrencyViewProtocol?
    var interactor: CurrencyInteractorProtocol?
    private let router: CurrencyWireframeProtocol

    init(interface: CurrencyViewProtocol, interactor: CurrencyInteractorProtocol?, router: CurrencyWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension CurrencyPresenter: CurrencyPresenterProtocol {
    
    func notifyFetchCurrencyBitcoin() {
        self.interactor?.fetchCurrencyBitcoin()
    }
    
    func notifyDisplayCurrencyBitcoin(currencyData: [BitcoinEntity]) {
        self.view?.displayCurrencyBitcoin(currencyData: currencyData)
    }
    
}
