//
//  CurrencyProtocols.swift
//  currency_btc
//
//  Created Phattarapon Jungtakarn on 19/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol CurrencyWireframeProtocol: class {

}
//MARK: Presenter -
protocol CurrencyPresenterProtocol: class {
    func notifyFetchCurrencyBitcoin()
    func notifyDisplayCurrencyBitcoin(currencyData: [BitcoinEntity])
}

//MARK: Interactor -
protocol CurrencyInteractorProtocol: class {
    var presenter: CurrencyPresenterProtocol?  { get set }
    func fetchCurrencyBitcoin()
}

//MARK: View -
protocol CurrencyViewProtocol: class {
    var presenter: CurrencyPresenterProtocol?  { get set }
    func displayCurrencyBitcoin(currencyData: [BitcoinEntity])
}
