//
//  CurrencyInteractor.swift
//  currency_btc
//
//  Created Phattarapon Jungtakarn on 19/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CurrencyInteractor {

    weak var presenter: CurrencyPresenterProtocol?
    
    init() {
        self.startUpdatingData()
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    func startUpdatingData() {
        Timer.scheduledTimer(timeInterval: 60.0, target: self, selector: #selector(updateData), userInfo: nil, repeats: true)
    }
    
    @objc func updateData() {
        self.fetchCurrencyBitcoin()
    }
    
}

extension CurrencyInteractor: CurrencyInteractorProtocol {
    
    func fetchCurrencyBitcoin() {
        CurrencyAPIHelper.sharedInstance().fetchCurrencyBitcoin(completion: { statusFetchCurrencyBitcoin in
            if statusFetchCurrencyBitcoin == "ok" {
                if let dataCurrency = UserSession.shared.getCurrencyBTC() {
                    self.presenter?.notifyDisplayCurrencyBitcoin(currencyData: [dataCurrency])
                }
            } else {
                //error fetch data
            }
        })
    }
    
}
