//
//  CurrencyRouter.swift
//  currency_btc
//
//  Created Phattarapon Jungtakarn on 19/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CurrencyRouter {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = CurrencyViewController(nibName: nil, bundle: nil)
        let interactor = CurrencyInteractor()
        let router = CurrencyRouter()
        let presenter = CurrencyPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        view.setTabbarImage("ic_currency", title: "Currency")
        
        return view
    }
}
 
extension CurrencyRouter: CurrencyWireframeProtocol {
    
}
