//
//  TabbarViewController.swift
//  currency_btc
//
//  Created Phattarapon Jungtakarn on 19/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TabbarViewController: UITabBarController, UITabBarControllerDelegate {

    var presenter: TabbarPresenterProtocol?
    var firstRun: Bool = true
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.navigationController?.navigationBar.isHidden = true
        self.delegate = self
        self.tabBar.isTranslucent = false
        self.tabBar.tintColor = UIColor.blue
        self.tabBar.barTintColor = UIColor.white
        self.tabBar.backgroundColor = UIColor.white
        self.tabBar.unselectedItemTintColor = UIColor.gray
        self.tabBar.shadowImage = UIImage.init()
        self.tabBar.layer.shadowColor = UIColor.gray.cgColor
        self.tabBar.layer.shadowOpacity = 0.2
        self.tabBar.layer.shadowOffset = CGSize(width: 0, height: -2)
        self.tabBar.layer.shadowRadius = 1
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        // pre-load all child view controllers (issue#1)
        self.viewControllers?.forEach {
            if let nav = $0 as? UINavigationController {
                let _ = nav.viewControllers[0].view
            } else {
                let _ = $0.view
            }
        }
        
        self.presenter?.notifyViewLoaded()
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        let noOfItems = CGFloat(tabBar.items!.count)
        let perItemSize = CGSize(width: tabBar.frame.width / noOfItems, height: tabBar.frame.height)
        self.tabBar.selectionIndicatorImage = (UIImage.imageWithColor(color: UIColor.white, size: perItemSize) as AnyObject).resizableImage(withCapInsets: UIEdgeInsets.zero)
        
        // removes default border
        self.tabBar.frame.size.width = self.view.frame.width + 4
        self.tabBar.frame.origin.x = -2
    }
}

extension TabbarViewController: TabbarViewProtocol {
    
    func displayTap(index: Int) {
        let itemCount = self.tabBar.items?.count
        if let _ = self.tabBar.items {
            self.selectedIndex = index
        }
    }
    
}

