//
//  TabbarRouter.swift
//  currency_btc
//
//  Created Phattarapon Jungtakarn on 19/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TabbarRouter {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = TabbarViewController(nibName: nil, bundle: nil)
        let interactor = TabbarInteractor()
        let router = TabbarRouter()
        let presenter = TabbarPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        view.viewControllers = [
            CurrencyRouter.createModule(),
            HistoryRouter.createModule()
        ]
        
        return view
    }
}

extension TabbarRouter: TabbarWireframeProtocol {
    
}
