//
//  TabbarPresenter.swift
//  currency_btc
//
//  Created Phattarapon Jungtakarn on 19/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TabbarPresenter {

    weak private var view: TabbarViewProtocol?
    var interactor: TabbarInteractorProtocol?
    private let router: TabbarWireframeProtocol

    init(interface: TabbarViewProtocol, interactor: TabbarInteractorProtocol?, router: TabbarWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension TabbarPresenter: TabbarPresenterProtocol {
    
    func notifyViewLoaded() {
        self.view?.displayTap(index: 0)
    }
    
    @objc func notifyTabSelectorCall() {
        self.view?.displayTap(index: 0)
    }
    
    @objc func notifyTabSelectorDaily() {
        self.view?.displayTap(index: 1)
    }
    
    @objc func notifyTabSettingSelector() {
        self.view?.displayTap(index: 2)
    }
    
    @objc func notifyTabVideoCallSelector() {
        self.view?.displayTap(index: 0)
    }
    
}
