//
//  TabbarInteractor.swift
//  currency_btc
//
//  Created Phattarapon Jungtakarn on 19/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TabbarInteractor {

    weak var presenter: TabbarPresenterProtocol?
}

extension TabbarInteractor: TabbarInteractorProtocol {
    
}
