//
//  TabbarProtocols.swift
//  currency_btc
//
//  Created Phattarapon Jungtakarn on 19/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol TabbarWireframeProtocol: class {

}
//MARK: Presenter -
protocol TabbarPresenterProtocol: class {
    func notifyViewLoaded()
}

//MARK: Interactor -
protocol TabbarInteractorProtocol: class {
    var presenter: TabbarPresenterProtocol?  { get set }
}

//MARK: View -
protocol TabbarViewProtocol: class {
    var presenter: TabbarPresenterProtocol?  { get set }
    func displayTap(index: Int)
}
